
import '../styles/globals.css'; // If styles is inside src
// ye styles folder or phir oss k andar file hamare pass src k andar hy tho iss wja se mene yaha pr .. dot lagaye hy etc.

// import '@styles/globals.css';
// agr aap ko iss trha ka import chaye hy tho phir aap simply jsconfig.json me ja kr wha ase forward slash / ko hata dena bs sirf @ iss ko rehnay dena simple
// "@/*": ["./*"] yaha se iss forward slash like "@*": ["./*"] this simple.

import 'bootstrap/dist/css/bootstrap.min.css'; // Import Bootstrap CSS
// import 'bootstrap/dist/js/bootstrap.bundle.min.js';


import Nav from "@components/Nav";
// yaha pr mene navabar ko import kiya howa hy.
import Provider from "@components/Provider";
// yaha pr mene provider ko import kiya howa hy.

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* yaha pr mene Navbar k component ko call kiya howa hy q k ye same hota hy har page me etc. */}
        <center>
          <Nav /> 
        </center>
        {children}
      </body>
    </html>
  );
}
